### ISSUE TITLE
Plugin failed to decode: Missing description

### ISSUE THREAD

**Issue by kubouch** [cptpiepmatz/nu-jupyter-kernel#2]
On the latest main of Nushell (0.97.2, commit 712fec166d7fed06022c654b756c7c130215d5f0), attempting to `plugin add ~/.cargo/bin/nu_plugin_plotters` gives the following error message:
```
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: missing field `description`
```

I cloned this repo (commit 10195b35770e903b18b38a60c47d81220df7306c) and ran `cd crates/nu_plugin_plotters` + `cargo install --path .` to install the plugin.

**Comment by kubouch** [comment]
Now it succeeded, but all other plugins report the following message:
```
Error: nu::shell::plugin_registry_data_invalid

  × The registered plugin data for `gstat` is invalid
  help: plugin add '/home/zadnik/.cargo/bin/nu_plugin_gstat'
```
So I'm not sure what's going on actually...

After deleting `$nu.plugin-path` and `plugin add`ing all my plugins except `nu_plugin_plotters`, the plugins work fine, but `plugin add ~/.cargo/bin/nu_plugin_plotters` yields again the error in the OP.

**Comment by cptpiepmatz** [comment]
Ok, I found the issue, https://github.com/nushell/nushell/pull/13598 changed the `Command` and `SimplePluginCommand` traits to use `description` instead of `usage`, this causes the plugin to break as it builds against `0.97.1`.

To isolate this I created a little Dockerfile that shows that issue:
```Dockerfile
FROM rust:1.80
RUN cargo install --git https://github.com/nushell/nushell.git --tag 0.97.1 nu
# RUN cargo install --git https://github.com/nushell/nushell.git --rev 712fec166d7fed06022c654b756c7c130215d5f0 nu
RUN cargo install --git https://github.com/cptpiepmatz/nu-jupyter-kernel.git nu_plugin_plotters
RUN mkdir -p /root/.config/nushell/
RUN nu -c "plugin add /usr/local/cargo/bin/nu_plugin_plotters"
ENTRYPOINT ["nu"]
```

Building with `0.97.1` works just fine, but the commit you mentioned, which includes https://github.com/nushell/nushell/pull/13598, won't build.

I try to build this repo against a tagged version, so this issue will stay open until a new version of nu gets released or I need a feature from the nushell repo.

**Comment by fdncred** [comment]
I didn't have issues with 0.97.2 but I had to change all the "usage" and "extra_usage" instance to "description" and "extra_description", and of course point the cargo.toml to my nushell local repo. After that, everything worked fine yesterday.

**Comment by cptpiepmatz** [comment]
This is fixed now
